### ISSUE TITLE
ReviewsFetcherThread is not pulling review for the first while loop iteration

### ISSUE THREAD

**Issue by felipegutierrez** [simplesteph/medium-blog-kafka-udemy#5] opened 2020-08-07 08:20 UTC
Hi @simplesteph , I am implementing the assignment as you suggested on your Kafka Series courses. I realized that the code at https://github.com/simplesteph/medium-blog-kafka-udemy/blob/master/udemy-reviews-producer/src/main/java/com/github/simplesteph/kafka/producer/udemy/runnable/ReviewsFetcherThread.java#L40 with a while(keepOnRunning) loop needs to run at least once with 0 reviews in order to get the reviews on the next iteration. If you would like I can push my code to your review.

**Comment by GiuseppeMP** [comment] 2021-06-15 01:15
@felipegutierrez  See PR #11. 😄

**Comment by GiuseppeMP** [comment] 2021-06-15 01:18
duplicate of #11

**Closed as completed** 2021-06-15 06:56 UTC
